language: python
sudo: false
python:
  - "2.7"
  - "3.4"

install:
  - pip install --use-mirrors pep8 pyflakes
  - pip install -r requirements.txt

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 -n -w --no-diffs tinyber; fi
  - pep8 --version
  - pep8 scripts tests tinyber

script:
  - python setup.py test
